### ISSUE TITLE
Couldnt import to Ghidra

### ISSUE THREAD

**Issue by umtkyck** [esaulenka/ghidra_STM8#5]
Hi,

Can you pls give little bit cue on importing stm8 to Ghidra. Current copying to extension folder didnt help me.

Also i couldnt find the language on tool.

Is there any SVD file that you know for stm8s?

**Comment by derbroti** [comment]
Try putting the extension folder into `./Ghidra/Extensions/` **not** `./Extensions/`.

Putting it there gave me an STM8 entry in the CodeBrowser under Help -> Installed Processors.
