### ISSUE TITLE
Failing to disassemble, help wanted

### ISSUE THREAD

**Issue by gustavolaureano** [esaulenka/ghidra_STM8#7]
Hi, I'm trying to decompile a binary using the extension, but it's not disassembling it correctly:

![Import Results Summary](https://user-images.githubusercontent.com/25323632/142205426-5905948d-e52d-4a0d-82cf-e3b23b0857bf.png)

![CodeBrowser](https://user-images.githubusercontent.com/25323632/142205441-678f38f7-cabe-447f-9c02-ab47e079e03d.png)

I also disassembled it using naken_util, and it was correctly disassembled:

![naken](https://user-images.githubusercontent.com/25323632/142205678-eacaa7ad-3a1c-407d-ae78-af052dd4f665.png)

This is my first time playing around with Ghidra, am I doing something wrong, or is the plugin broken on my Ghidra version, 10.0.4 ?

Could somebody help me?

Thanks!

**Comment by gustavolaureano** [comment]
Now I figured out, the "Analyze" was not able to trigger a disassemble, but manually selecting the memory area and asking to disassemble worked (y)

**Comment by esaulenka** [comment]
Automatic analyzer uses a lot of heuristic rules. But in your case there is no patterns for function start (I didnt implemented it), no strings (this is rare case in embedded software), no pointers (Ghidra correctly recognizes it only on 32-bit and 64-bit CPUs), no standard entry point (here needed loader for STM8. I didnt figure out, how to do it).

Therefore, the working way - to find the entry point (vectors table) and manually start disassembly on it.

**Comment by gustavolaureano** [comment]
Hi @esaulenka , yes, I figured it out today :) This is my first time doing RE / playing with Ghidra, so I am climbing multiple learning curves at the same time, but I am slowly making progress.

Yesterday I selected the entire flash content and "decompiled", but it also brought a lot of garbage code, as const data stored in the flash was also misinterpreted as instructions

So today I took this approach you just suggested, used the vector table as starting point and decompiled from there, in this way only real code was found!

Thanks for implementing this module, it is being very useful :)
